Questions
1.Show the employee names and corresponding job_titles without using JOIN query
2.Do the question no 1 using JOIN query
3.Show the name of the employee and the job_title who receives the maximum salary
4.Show the list of employee name and corresponding manager names.

1.ans:

SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES,DEPARTMENTS
WHERE EMPLOYEES.EMPLOYEE_ID = DEPARTMENTS.DEPARTMENT_ID

2.ANS:


SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
3.ANS: 
SELECT E.FIRST_NAME,J.JOB_TITLE
FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE E.SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES)

4.ANS:
SELECT E.FIRST_NAME,M.FIRST_NAME
 FROM EMPLOYEES E JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID;
 
 